### ISSUE TITLE
弄一个app吧，给家里需要练习英语的人用。小程序也行

### ISSUE THREAD

**Issue by cuimingjun-fenrir** [Orenoid/BabelDuck#27]
RT

**Comment by Orenoid** [comment]
个人时间有限，暂无开发 app 或小程序计划，后续会针对移动端界面做适配，这个是目前比较可行的方案。

**Comment by Orenoid** [comment]
该需求跟这个 [issue](https://github.com/Orenoid/BabelDuck/issues/26) 合并处理。  
先关闭了，有需要可重新打开。
